title: "Mohit Kumar"
email: mohit.ahir6666@Gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello guys My name is Mohit kumar, I belong to punjab. I am an independent security researcher,I have done BTech in Computer Science and Engineering. I have done the CEHv10 certification. I found Many bugs in many organozations
baseurl: "/" 
url: "https://MohitKumar0786.github.io/" 
twitter_username: MohitAhir01
github_username:  Mohitkumar0786
Hackerone_username: mohit1247
Linkedin_username: mohitkumar786

sass:
  sass_dir: _sass

icon: /assets/img/icon2.png
